/**
 * Render every Open Graph card on the site to disk, for review.
 *
 * The cards are generated by Satori at build time, so this does not create
 * them — it *collects* them, by asking each page for the `og:image` it
 * actually declares and saving that exact PNG. Reading the declared URL
 * rather than guessing a route shape is the point: it means this script
 * cannot pass on a page whose metadata is wrong, because the file it saves
 * is the file a crawler would fetch.
 *
 * The route list comes from /sitemap.xml, so coverage is whatever the site
 * says is indexable. A page with a card but no sitemap entry, or an entry
 * with no card, both show up in the summary rather than passing silently.
 *
 * Usage:
 *   node scripts/render-og.mjs [--base http://localhost:3100] [--out og-out]
 *
 * Point it at a production server (`npm run build && npm start`) rather than
 * dev: in dev every card pays a Turbopack compile first, and a stale dev
 * bundle will happily hand back a card the production build would not.
 */

import { mkdir, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";

const argv = process.argv.slice(2);
const arg = (name, fallback) => {
  const i = argv.indexOf(name);
  return i === -1 ? fallback : argv[i + 1];
};

const BASE = arg("--base", "http://localhost:3100").replace(/\/$/, "");
const OUT = arg("--out", "og-out");

/** `/` becomes `index.png`; everything else mirrors its route path. */
function localPath(route) {
  const clean = route.replace(/^\/+|\/+$/g, "");
  return clean === "" ? "index" : clean.replace(/\//g, "--");
}

async function get(url, { as = "text" } = {}) {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return as === "buffer" ? Buffer.from(await res.arrayBuffer()) : res.text();
}

async function main() {
  console.log(`base ${BASE}\nout  ${OUT}\n`);

  const sitemap = await get(`${BASE}/sitemap.xml`);
  const routes = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => {
    // Absolute, because metadataBase resolves against the configured site URL
    // and the dev server is not that URL.
    const u = new URL(m[1].trim());
    return u.pathname + (u.search || "");
  });

  if (!routes.length) throw new Error("no <loc> entries in /sitemap.xml");
  routes.sort();
  console.log(`${routes.length} routes from /sitemap.xml\n`);

  await rm(OUT, { recursive: true, force: true });

  const failures = [];
  const noCard = [];
  let written = 0;
  let bytes = 0;

  // Sequential on purpose. These renders are CPU-bound in Satori and Resvg;
  // running them concurrently just makes every one of them slower and the
  // dev server's compile queue deeper. At ~150 cards this is a couple of
  // minutes either way.
  for (const [i, route] of routes.entries()) {
    const page = `${BASE}${route}`;
    process.stdout.write(
      `[${String(i + 1).padStart(3)}/${routes.length}] ${route.padEnd(52)}`,
    );

    try {
      const html = await get(page);
      const og = html.match(/<meta\s+property="og:image"\s+content="([^"]+)"/)?.[1];
      if (!og) {
        noCard.push(route);
        console.log("NO og:image");
        continue;
      }

      // The declared URL is absolute and points at metadataBase, which is
      // https://lattice.sh in production and unreachable from here. Re-host it
      // onto the server we are actually talking to, keeping path and query —
      // the query is the metadata route id and is required.
      const u = new URL(og);
      const png = await get(BASE + u.pathname + u.search, { as: "buffer" });

      const dest = join(OUT, `${localPath(route)}.png`);
      await mkdir(join(OUT, ...route.split("/").filter(Boolean).slice(0, -1)), {
        recursive: true,
      }).catch(() => {});
      await writeFile(dest, png);

      written++;
      bytes += png.length;
      console.log(`ok  ${(png.length / 1024).toFixed(0)} KB`);
    } catch (err) {
      failures.push([route, err.message]);
      console.log(`FAIL ${err.message}`);
    }
  }

  console.log(`\n${"-".repeat(60)}`);
  console.log(`written  ${written}/${routes.length}`);
  console.log(`total    ${(bytes / 1024 / 1024).toFixed(1)} MB`);
  console.log(`mean     ${Math.round(bytes / Math.max(written, 1) / 1024)} KB`);

  if (noCard.length) {
    console.log(`\nno og:image (${noCard.length}):`);
    noCard.forEach((r) => console.log(`  ${r}`));
  }
  if (failures.length) {
    console.log(`\nfailed (${failures.length}):`);
    failures.forEach(([r, m]) => console.log(`  ${r} — ${m}`));
    process.exitCode = 1;
  }
}

await main();